/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesInteriorDesignRouteImport } from './routes/services.interior-design'
import { Route as ServicesExecutiveSearchRouteImport } from './routes/services.executive-search'
import { Route as ServicesBimRouteImport } from './routes/services.bim'
import { Route as ServicesArchitectureRouteImport } from './routes/services.architecture'
import { Route as IndustriesWorkplaceRouteImport } from './routes/industries.workplace'
import { Route as IndustriesUrbanPlanningRouteImport } from './routes/industries.urban-planning'
import { Route as IndustriesRetailRouteImport } from './routes/industries.retail'
import { Route as IndustriesResidentialRouteImport } from './routes/industries.residential'
import { Route as IndustriesIndustrialRouteImport } from './routes/industries.industrial'
import { Route as IndustriesHospitalityRouteImport } from './routes/industries.hospitality'
import { Route as IndustriesHealthcareRouteImport } from './routes/industries.healthcare'
import { Route as IndustriesEducationRouteImport } from './routes/industries.education'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInteriorDesignRoute = ServicesInteriorDesignRouteImport.update({
  id: '/services/interior-design',
  path: '/services/interior-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesExecutiveSearchRoute = ServicesExecutiveSearchRouteImport.update({
  id: '/services/executive-search',
  path: '/services/executive-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBimRoute = ServicesBimRouteImport.update({
  id: '/services/bim',
  path: '/services/bim',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesArchitectureRoute = ServicesArchitectureRouteImport.update({
  id: '/services/architecture',
  path: '/services/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesWorkplaceRoute = IndustriesWorkplaceRouteImport.update({
  id: '/industries/workplace',
  path: '/industries/workplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesUrbanPlanningRoute = IndustriesUrbanPlanningRouteImport.update({
  id: '/industries/urban-planning',
  path: '/industries/urban-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRetailRoute = IndustriesRetailRouteImport.update({
  id: '/industries/retail',
  path: '/industries/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesResidentialRoute = IndustriesResidentialRouteImport.update({
  id: '/industries/residential',
  path: '/industries/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndustrialRoute = IndustriesIndustrialRouteImport.update({
  id: '/industries/industrial',
  path: '/industries/industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHospitalityRoute = IndustriesHospitalityRouteImport.update({
  id: '/industries/hospitality',
  path: '/industries/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHealthcareRoute = IndustriesHealthcareRouteImport.update({
  id: '/industries/healthcare',
  path: '/industries/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesEducationRoute = IndustriesEducationRouteImport.update({
  id: '/industries/education',
  path: '/industries/education',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/hospitality': typeof IndustriesHospitalityRoute
  '/industries/industrial': typeof IndustriesIndustrialRoute
  '/industries/residential': typeof IndustriesResidentialRoute
  '/industries/retail': typeof IndustriesRetailRoute
  '/industries/urban-planning': typeof IndustriesUrbanPlanningRoute
  '/industries/workplace': typeof IndustriesWorkplaceRoute
  '/services/architecture': typeof ServicesArchitectureRoute
  '/services/bim': typeof ServicesBimRoute
  '/services/executive-search': typeof ServicesExecutiveSearchRoute
  '/services/interior-design': typeof ServicesInteriorDesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/hospitality': typeof IndustriesHospitalityRoute
  '/industries/industrial': typeof IndustriesIndustrialRoute
  '/industries/residential': typeof IndustriesResidentialRoute
  '/industries/retail': typeof IndustriesRetailRoute
  '/industries/urban-planning': typeof IndustriesUrbanPlanningRoute
  '/industries/workplace': typeof IndustriesWorkplaceRoute
  '/services/architecture': typeof ServicesArchitectureRoute
  '/services/bim': typeof ServicesBimRoute
  '/services/executive-search': typeof ServicesExecutiveSearchRoute
  '/services/interior-design': typeof ServicesInteriorDesignRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/hospitality': typeof IndustriesHospitalityRoute
  '/industries/industrial': typeof IndustriesIndustrialRoute
  '/industries/residential': typeof IndustriesResidentialRoute
  '/industries/retail': typeof IndustriesRetailRoute
  '/industries/urban-planning': typeof IndustriesUrbanPlanningRoute
  '/industries/workplace': typeof IndustriesWorkplaceRoute
  '/services/architecture': typeof ServicesArchitectureRoute
  '/services/bim': typeof ServicesBimRoute
  '/services/executive-search': typeof ServicesExecutiveSearchRoute
  '/services/interior-design': typeof ServicesInteriorDesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/industries/education'
    | '/industries/healthcare'
    | '/industries/hospitality'
    | '/industries/industrial'
    | '/industries/residential'
    | '/industries/retail'
    | '/industries/urban-planning'
    | '/industries/workplace'
    | '/services/architecture'
    | '/services/bim'
    | '/services/executive-search'
    | '/services/interior-design'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/industries/education'
    | '/industries/healthcare'
    | '/industries/hospitality'
    | '/industries/industrial'
    | '/industries/residential'
    | '/industries/retail'
    | '/industries/urban-planning'
    | '/industries/workplace'
    | '/services/architecture'
    | '/services/bim'
    | '/services/executive-search'
    | '/services/interior-design'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/industries/education'
    | '/industries/healthcare'
    | '/industries/hospitality'
    | '/industries/industrial'
    | '/industries/residential'
    | '/industries/retail'
    | '/industries/urban-planning'
    | '/industries/workplace'
    | '/services/architecture'
    | '/services/bim'
    | '/services/executive-search'
    | '/services/interior-design'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRoute
  IndustriesEducationRoute: typeof IndustriesEducationRoute
  IndustriesHealthcareRoute: typeof IndustriesHealthcareRoute
  IndustriesHospitalityRoute: typeof IndustriesHospitalityRoute
  IndustriesIndustrialRoute: typeof IndustriesIndustrialRoute
  IndustriesResidentialRoute: typeof IndustriesResidentialRoute
  IndustriesRetailRoute: typeof IndustriesRetailRoute
  IndustriesUrbanPlanningRoute: typeof IndustriesUrbanPlanningRoute
  IndustriesWorkplaceRoute: typeof IndustriesWorkplaceRoute
  ServicesArchitectureRoute: typeof ServicesArchitectureRoute
  ServicesBimRoute: typeof ServicesBimRoute
  ServicesExecutiveSearchRoute: typeof ServicesExecutiveSearchRoute
  ServicesInteriorDesignRoute: typeof ServicesInteriorDesignRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/interior-design': {
      id: '/services/interior-design'
      path: '/services/interior-design'
      fullPath: '/services/interior-design'
      preLoaderRoute: typeof ServicesInteriorDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/executive-search': {
      id: '/services/executive-search'
      path: '/services/executive-search'
      fullPath: '/services/executive-search'
      preLoaderRoute: typeof ServicesExecutiveSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bim': {
      id: '/services/bim'
      path: '/services/bim'
      fullPath: '/services/bim'
      preLoaderRoute: typeof ServicesBimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/architecture': {
      id: '/services/architecture'
      path: '/services/architecture'
      fullPath: '/services/architecture'
      preLoaderRoute: typeof ServicesArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/workplace': {
      id: '/industries/workplace'
      path: '/industries/workplace'
      fullPath: '/industries/workplace'
      preLoaderRoute: typeof IndustriesWorkplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/urban-planning': {
      id: '/industries/urban-planning'
      path: '/industries/urban-planning'
      fullPath: '/industries/urban-planning'
      preLoaderRoute: typeof IndustriesUrbanPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/retail': {
      id: '/industries/retail'
      path: '/industries/retail'
      fullPath: '/industries/retail'
      preLoaderRoute: typeof IndustriesRetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/residential': {
      id: '/industries/residential'
      path: '/industries/residential'
      fullPath: '/industries/residential'
      preLoaderRoute: typeof IndustriesResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/industrial': {
      id: '/industries/industrial'
      path: '/industries/industrial'
      fullPath: '/industries/industrial'
      preLoaderRoute: typeof IndustriesIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/hospitality': {
      id: '/industries/hospitality'
      path: '/industries/hospitality'
      fullPath: '/industries/hospitality'
      preLoaderRoute: typeof IndustriesHospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/healthcare': {
      id: '/industries/healthcare'
      path: '/industries/healthcare'
      fullPath: '/industries/healthcare'
      preLoaderRoute: typeof IndustriesHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/education': {
      id: '/industries/education'
      path: '/industries/education'
      fullPath: '/industries/education'
      preLoaderRoute: typeof IndustriesEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRoute,
  IndustriesEducationRoute: IndustriesEducationRoute,
  IndustriesHealthcareRoute: IndustriesHealthcareRoute,
  IndustriesHospitalityRoute: IndustriesHospitalityRoute,
  IndustriesIndustrialRoute: IndustriesIndustrialRoute,
  IndustriesResidentialRoute: IndustriesResidentialRoute,
  IndustriesRetailRoute: IndustriesRetailRoute,
  IndustriesUrbanPlanningRoute: IndustriesUrbanPlanningRoute,
  IndustriesWorkplaceRoute: IndustriesWorkplaceRoute,
  ServicesArchitectureRoute: ServicesArchitectureRoute,
  ServicesBimRoute: ServicesBimRoute,
  ServicesExecutiveSearchRoute: ServicesExecutiveSearchRoute,
  ServicesInteriorDesignRoute: ServicesInteriorDesignRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
